In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import KFold   #For K-fold cross validation
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics

In [5]:
animal =pd.read_csv("shelter_animal/train.csv")

In [6]:
animal

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,Intact Female,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Tabby
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,Spayed Female,5 months,American Pit Bull Terrier Mix,Red/White
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,Spayed Female,1 year,Cairn Terrier,White
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,Spayed Female,2 years,Miniature Schnauzer Mix,Silver
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,Neutered Male,4 years,Pit Bull Mix,Brown
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,Neutered Male,2 years,Yorkshire Terrier Mix,Black/Red
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Great Pyrenees Mix,White/Cream
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Orange Tabby/White
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,Intact Female,2 weeks,Pit Bull Mix,Brown/White
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,Intact Female,2 years,Angora Mix,White
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Flat Coat Retriever Mix,Black
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,Intact Male,2 months,Queensland Heeler Mix,Black/White
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,Spayed Female,1 year,Domestic Shorthair Mix,White
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,Spayed Female,2 years,Plott Hound/Boxer,Brown Brindle/White
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Black/Brown
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,Intact Female,1 month,Domestic Shorthair Mix,Orange Tabby
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,Spayed Female,6 months,American Staffordshire Terrier Mix,Chocolate/White
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,Spayed Female,5 years,Chihuahua Shorthair Mix,White/Tan
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Cream Tabby/White
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,Neutered Male,7 years,Russian Blue Mix,Blue
30,A718535,NaN,2016-01-01 13:57:00,Euthanasia,Suffering,Cat,Spayed Female,3 years,Domestic Shorthair Mix,Calico
31,A707341,Murphy,2015-07-15 15:25:00,Transfer,Partner,Dog,Intact Male,4 months,Labrador Retriever Mix,Black/White
32,A682532,NaN,2014-07-03 17:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Torbie
33,A666825,Jesse,2013-11-08 13:24:00,Return_to_owner,NaN,Dog,Neutered Male,5 years,Collie Smooth/German Shepherd,Brown/Black
34,A699723,Delgado,2015-04-11 16:01:00,Transfer,Partner,Dog,Neutered Male,3 years,Chihuahua Shorthair Mix,Brown
35,A668626,NaN,2013-12-06 14:55:00,Euthanasia,Suffering,Dog,Intact Male,3 years,Labrador Retriever Mix,Yellow
36,A657085,Pony Boy,2013-10-24 11:22:00,Return_to_owner,NaN,Dog,Neutered Male,3 years,Pit Bull Mix,Brown/White
37,A682413,NaN,2014-07-02 13:37:00,Transfer,Partner,Cat,Intact Male,2 months,Domestic Shorthair Mix,Blue/White
38,A702655,Mica,2015-08-11 00:00:00,Transfer,Partner,Cat,Neutered Male,4 months,Domestic Shorthair Mix,Black/White
39,A707503,NaN,2015-07-14 12:16:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
40,A697199,Pilar,2015-04-04 17:26:00,Adoption,NaN,Cat,Spayed Female,7 years,Domestic Shorthair Mix,Blue Tabby
41,A705598,NaN,2015-06-23 13:25:00,Transfer,Partner,Cat,Intact Male,2 months,Domestic Shorthair Mix,Orange Tabby
42,A668388,Lucy,2013-12-09 15:04:00,Transfer,Partner,Cat,Intact Female,2 months,Domestic Shorthair Mix,Brown Tabby
43,A671181,NaN,2014-01-21 15:15:00,Transfer,SCRP,Cat,Intact Male,4 years,Domestic Longhair Mix,Black/White
44,A676766,Ali,2014-05-28 15:52:00,Adoption,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Black/White
45,A686716,Chester,2014-08-27 07:50:00,Return_to_owner,NaN,Dog,Neutered Male,12 years,Beagle,Tricolor
46,A684475,Daisy,2014-08-05 11:15:00,Return_to_owner,NaN,Cat,Spayed Female,9 years,Domestic Shorthair Mix,White/Black
47,A701804,NaN,2015-05-05 11:46:00,Transfer,Partner,Cat,Intact Female,3 weeks,Domestic Shorthair Mix,Black
48,A697852,Edith,2015-03-09 17:57:00,Adoption,NaN,Dog,Spayed Female,5 months,German Shepherd Mix,Black/Brown
49,A666092,NaN,2013-10-30 15:37:00,Euthanasia,Aggressive,Dog,Intact Male,6 years,Pit Bull/Labrador Retriever,Chocolate/White
50,A684050,NaN,2014-07-28 09:00:00,Transfer,SCRP,Cat,Intact Female,1 year,Domestic Shorthair Mix,Tortie
51,A710107,Caty,2015-10-19 18:58:00,Adoption,NaN,Cat,Spayed Female,3 months,Domestic Shorthair Mix,Brown Tabby
52,A682347,NaN,2014-06-26 17:16:00,Transfer,Partner,Cat,Intact Female,3 weeks,Domestic Shorthair Mix,Blue Tabby/White
53,A701627,Gabe,2015-05-14 12:07:00,Adoption,NaN,Dog,Neutered Male,2 years,Blue Lacy Mix,Gray/White
54,A690902,Beth,2014-11-18 16:05:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Orange Tabby/White
55,A712979,NaN,2015-10-04 15:02:00,Transfer,Partner,Cat,Intact Male,1 weeks,Domestic Shorthair Mix,Black
56,A707687,Bashful,2015-08-16 13:52:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Calico
57,A683443,NaN,2014-07-18 16:23:00,Transfer,Partner,Dog,Intact Male,1 year,Chihuahua Shorthair Mix,Tan
58,A597644,Lola,2014-09-16 14:05:00,Return_to_owner,NaN,Dog,Spayed Female,4 years,Black Mouth Cur Mix,Tan/Black
59,A682784,Sugar,2014-07-07 12:38:00,Adoption,NaN,Dog,Neutered Male,2 years,Dachshund/Beagle,Brown/White
,...,...,...,...,...,...,...,...,...,...

In [4]:
animal.describe()

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
count,26729,19038,26729,26729,13117,26729,26728,26711,26729,26729
unique,26729,6374,22918,5,16,2,5,44,1380,366
top,A691613,Max,2015-08-11 00:00:00,Adoption,Partner,Dog,Neutered Male,1 year,Domestic Shorthair Mix,Black/White
freq,1,136,19,10769,7816,15595,9779,3969,8810,2824

In [8]:
animal.drop('Name', axis=1, inplace=True)

In [10]:
animal.describe()

,AnimalID,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
count,26729,26729,26729,13117,26729,26728,26711,26729,26729
unique,26729,22918,5,16,2,5,44,1380,366
top,A691613,2015-08-11 00:00:00,Adoption,Partner,Dog,Neutered Male,1 year,Domestic Shorthair Mix,Black/White
freq,1,19,10769,7816,15595,9779,3969,8810,2824