In [18]:
import pandas as pd
import numpy as np
%matplotlib inline

In [19]:
data = pd.read_csv('train.csv')
data= data.drop(['Outlet_Identifier'],1)
data= data.drop(['Item_Identifier'],1)
data['Outlet_Size'].fillna('Medium', inplace = True)
#data = data[:15]
min_elements_in_leaf = 3
data2 = pd.DataFrame()
data2['Outlet_Size'] = data['Outlet_Size']
data2['Outlet_Type'] = data['Outlet_Type']
data2['Item_Outlet_Sales'] = data['Item_Outlet_Sales']
data = data2

for col in [ 'Outlet_Size','Outlet_Type']:
    data[col] = data[col].astype('category')

cat_col = []

for col in data:
    if data[col].dtype.name == 'category':
        cat_col.append(col)

result = 'Item_Outlet_Sales'
attrib_value_pair_used = {}

some_avail = {}
for col in data:
    some_avail[col] = 1

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
clf = DecisionTreeClassifier(criterion='mse',max_depth=8, min_samples_split=4, min_samples_leaf=1,max_features = 4 )
clf.fit(data[col], data[result])

/home/fsftn/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

ValueError: Unknown label type: array([[ 3735.138 ],
       [  443.4228],
       [ 2097.27  ],
       ...,
       [ 1193.1136],
       [ 1845.5976],
       [  765.67  ]])

In [23]:
data

     Outlet_Size        Outlet_Type  Item_Outlet_Sales
0         Medium  Supermarket Type1          3735.1380
1         Medium  Supermarket Type2           443.4228
2         Medium  Supermarket Type1          2097.2700
3         Medium      Grocery Store           732.3800
4           High  Supermarket Type1           994.7052
5         Medium  Supermarket Type2           556.6088
6           High  Supermarket Type1           343.5528
7         Medium  Supermarket Type3          4022.7636
8         Medium  Supermarket Type1          1076.5986
9         Medium  Supermarket Type1          4710.5350
10        Medium  Supermarket Type1          1516.0266
11         Small  Supermarket Type1          2187.1530
12        Medium  Supermarket Type1          1589.2646
13         Small  Supermarket Type1          2145.2076
14          High  Supermarket Type1          1977.4260
15         Small  Supermarket Type1          1547.3192
16        Medium  Supermarket Type2          1621.8888
17        Medium  Supermarket Type1           718.3982
18        Medium  Supermarket Type3          2303.6680
19         Small  Supermarket Type1          2748.4224
20          High  Supermarket Type1          3775.0860
21        Medium  Supermarket Type3          4064.0432
22         Small  Supermarket Type1          1587.2672
23         Small      Grocery Store           214.3876
24         Small  Supermarket Type1          4078.0250
25        Medium  Supermarket Type1           838.9080
26         Small  Supermarket Type1          1065.2800
27          High  Supermarket Type1           308.9312
28        Medium      Grocery Store           178.4344
29         Small      Grocery Store           125.8362
...          ...                ...                ...
8493      Medium  Supermarket Type1          4727.1800
8494      Medium  Supermarket Type1          1637.8680
8495       Small  Supermarket Type1          4314.3840
8496      Medium  Supermarket Type1          3715.1640
8497       Small  Supermarket Type1          2247.0750
8498      Medium  Supermarket Type2          1601.2490
8499       Small  Supermarket Type1          2976.1260
8500      Medium  Supermarket Type1          1907.5170
8501      Medium  Supermarket Type1          1508.0370
8502      Medium  Supermarket Type1          3020.0688
8503       Small  Supermarket Type1          3392.9168
8504      Medium  Supermarket Type3          4138.6128
8505      Medium  Supermarket Type2          2117.2440
8506      Medium  Supermarket Type2          3944.8650
8507       Small  Supermarket Type1           515.9950
8508      Medium  Supermarket Type1          2587.9646
8509      Medium      Grocery Store           424.7804
8510       Small  Supermarket Type1          7182.6504
8511      Medium  Supermarket Type2          4207.8560
8512        High  Supermarket Type1          2479.4392
8513       Small  Supermarket Type1           595.2252
8514      Medium  Supermarket Type1           468.7232
8515      Medium  Supermarket Type2          1571.2880
8516      Medium  Supermarket Type2           858.8820
8517       Small  Supermarket Type1          3608.6360
8518        High  Supermarket Type1          2778.3834
8519      Medium  Supermarket Type1           549.2850
8520       Small  Supermarket Type1          1193.1136
8521      Medium  Supermarket Type2          1845.5976
8522       Small  Supermarket Type1           765.6700

[8523 rows x 3 columns]

In [35]:
clf = DecisionTreeRegressor( )
preds = ['Outlet_Type']
clf.fit(data[preds], data['Item_Outlet_Sales'])
from sklearn import tree
dot_file = tree.export_graphviz(clf.tree_, out_file='tree_d1.dot', feature_names=preds)  #export the tree to .dot file

ValueError: could not convert string to float: Supermarket Type1

In [34]:

from subprocess import check_call
check_call(['dot','-Tpng','tree_d1.dot','-o','OutputFilefinal.png'])

0