In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.cross_validation import KFold   #For K-fold cross validation
from sklearn.utils import shuffle

from IPython.display import Image
from IPython.core.display import HTML

/home/fsftn/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
all_years = pd.read_csv('s2017.csv') 
role = pd.read_csv('roles_2017.csv') 

all_years['player_name'] = all_years['fname'] + ' ' + all_years['sname']
all_years['base_price'] = all_years['Reserve Price Rs Lakh']
all_years[:5]

,List Sr. No.,fname,sname,Specialism,Reserve Price Rs Lakh,player_name,base_price
0,1,Faiz,Fazal,Batsman,30,Faiz Fazal,30
1,2,Martin,Guptill,Batsman,50,Martin Guptill,50
2,3,Alex,Hales,Batsman,100,Alex Hales,100
3,4,Eoin,Morgan,Batsman,200,Eoin Morgan,200
4,5,Jason,Roy,Batsman,100,Jason Roy,100

In [3]:
balls = []
runs = []
avg = []
srate2 = []
balls2 = []
runs2 = []
avg2 = []
srate = []
batsman = []
year = []
base_price  = []
buy_price  = []
for index, row in all_years.iterrows():
    
    
    
    
    
    pname = str(str(row['player_name']).replace(' ','+'))
    #print pname
    prole = role[role['pname'].str.find(pname) != -1] 
    if(len(prole) == 0):
        continue
    prole = prole.iloc[0]['role']
    
    fname = 'score_files/' + str('2017') + '_t20_' + pname + '.csv'
    #print fname
    fname2 =  'score_files/' + str('2017') + '_listA_' + pname + '.csv'
    
    #print fname
    if(prole == 0):
        continue
        
    if (os.path.isfile(fname) and os.path.isfile(fname2)):
        data = pd.read_csv(fname)
        
        data['balls']  =  data['balls'].astype('str') 
        data = data[data['balls'] != '\xc2\xa0']
        
        data['balls']  =  data['balls'].astype('float') 
        data['runs']  =  data['runs'].astype('float') 
        
        #data = data[data['runs'] != '\xc2\xa0']
        if(len(data) < 2):
            continue
            
        bprice  = str(str(row['base_price']).replace(',',''))
        bprice  = bprice.replace('$','')
        bprice = float(bprice)
        
        #b2price  = str(row['buy_price'].replace(',',''))
        #b2price  = b2price.replace('$','')
        #b2price = float(b2price)
        
    
        
        
        
        
        #t20 done now odi 
        
        
        
        
        data2 = pd.read_csv(fname2)
        
        data2['balls']  =  data2['balls'].astype('str') 
        data2 = data2[data2['balls'] != '\xc2\xa0']
        
        data2['balls']  =  data2['balls'].astype('float') 
        data2['runs']  =  data2['runs'].astype('float') 
        
        #data = data[data['runs'] != '\xc2\xa0']
        if(len(data2) < 2):
            continue
            
     
        batsman.append(pname)
        base_price.append(bprice) 
        #buy_price.append(b2price)
        #year.append(row['year'])
        balls.append(np.sum(data['balls']))
        runs.append(np.sum(data['runs']))
        avg.append(np.sum(data['runs'])/(len(data)))
        srate.append(np.mean([(r/b)*100 for r,b in zip(data['runs'], data['balls'])]))
        
        balls2.append(np.sum(data2['balls']))
        runs2.append(np.sum(data2['runs']))
        avg2.append(np.sum(data2['runs'])/(len(data2)))
        srate2.append(np.mean([(r/b)*100 for r,b in zip(data2['runs'], data2['balls'])]))
        print 'done for ',pname
             
        
    else:
        #print 'file no exists'
        print fname
        #continue

done for  Faiz+Fazal
done for  Martin+Guptill
done for  Alex+Hales
done for  Eoin+Morgan
done for  Jason+Roy
done for  Ross+Taylor
done for  Sean+Abbott
done for  Corey+Anderson
done for  Chris+Jordan
done for  Angelo+Mathews
score_files/2017_t20_Pawan+Negi.csv
done for  Benjamin+Stokes
done for  Jonny+Bairstow
done for  Dinesh+Chandimal
done for  Johnson+Charles
done for  Ben+Dunk
done for  Andre+Fletcher
score_files/2017_t20_Nicholas+Pooran.csv
score_files/2017_t20_Ankeet+Bawane.csv
done for  Unmukt+Chand
done for  Michael+Klinger
score_files/2017_t20_Umang+Sharma.csv
score_files/2017_t20_Prithvi+Shaw.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Shivam+Dube.csv
score_files/2017_t20_Praveen+Dubey.csv
score_files/2017_t20_Gowtham+K..csv
score_files/2017_t20_Mahipal+Lomror.csv
done for  Mohammad+Nabi
score_files/2017_t20_Rahul+Tewatia.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Mohit+Ahlawat.csv
score_files/2017_t20_Shreevats+Goswami.csv
score_files/2017_t20_Vishnu+Vinod.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
done for  Darren+Bravo
done for  Evin+Lewis
done for  Nic+Maddinson
done for  Marlon+Samuels
score_files/2017_t20_Manoj+Tiwari.csv
score_files/2017_t20_nan.csv
done for  Farhaan+Behardien
done for  Jason+Holder
score_files/2017_t20_Thisara+Perera.csv
score_files/2017_t20_Karn+Sharma.csv
done for  David+Wiese
done for  Chris+Woakes
score_files/2017_t20_nan.csv
done for  Niroshan+Dickwella
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Pramod+Chandila.csv
score_files/2017_t20_Paras+Dogra.csv
score_files/2017_t20_Aditya+Garhwal.csv
score_files/2017_t20_Amandeep+Khare.csv
score_files/2017_t20_Samarth+R..csv
score_files/2017_t20_Himanshu+Rana.csv
done for  D'Arcy+Short
score_files/2017_t20_nan.csv
score_files/2017_t20_Akash+Bhandari.csv
score_files/2017_t20_Aamir+Gani.csv
score_files/2017_t20_Rajagopal+Sathish.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Gitansh+Khera.csv
score_files/2017_t20_Mahesh+Rawat.csv
score_files/2017_t20_Dishant+Yagnik.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
done for  Neil+Broom
score_files/2017_t20_Tom+Bruce.csv
done for  Joe+Burns
done for  Callum+Ferguson
done for  Asela+Gunarathna
done for  Sam+Heazlett
done for  Kusal+Mendis
score_files/2017_t20_nan.csv
done for  Daniel+Christian
done for  Grant+Elliott
done for  Colin+Munro
score_files/2017_t20_Abhishek+Nayar.csv
done for  James+Neesham
done for  Wayne+Parnell
done for  Rovman+Powell
done for  Darren+Sammy
done for  Mitchell+Santner
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Prashant+Chopra.csv
score_files/2017_t20_Kumar+Deobrat.csv
score_files/2017_t20_Pavan+Deshpande.csv
score_files/2017_t20_Arjit+Gupta.csv
score_files/2017_t20_Manprit+Juneja.csv
score_files/2017_t20_Pratyush+Kumar.csv
score_files/2017_t20_Paul+Valthaty.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Chirag+Jani.csv
score_files/2017_t20_Akshay+Karnewar.csv
done for  Milind+Kumar
done for  Amit+Mishra
score_files/2017_t20_Yogesh+Nagar.csv
score_files/2017_t20_Biplab+Samantray.csv
done for  Shashank+Singh
score_files/2017_t20_Karanveer+Singh.csv
done for  Milind+Tandon
score_files/2017_t20_nan.csv
score_files/2017_t20_N.+Jagadeesan.csv
done for  Glenn+Phillips
score_files/2017_t20_Nakul+Sharma.csv
score_files/2017_t20_nan.csv
done for  Amit+Mishra
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
done for  Anton+Devcich
done for  Rayad+Emrit
score_files/2017_t20_Jeevan+Mendis.csv
score_files/2017_t20_Andile+Phehlukwayo.csv
done for  Seekkuge+Prasanna
done for  Dwaine+Pretorius
done for  Jesse+Ryder
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Ankit+Lamba.csv
score_files/2017_t20_Amit+Pachhara.csv
score_files/2017_t20_Sarthak+Ranjan.csv
done for  Alex+Ross
score_files/2017_t20_Jonty+Sidhu.csv
score_files/2017_t20_Tajendra+Singh.csv
score_files/2017_t20_Virat+Singh.csv
score_files/2017_t20_Chirag+Suri.csv
score_files/2017_t20_Shamsher+Yadav.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Subodh+Bhati.csv
score_files/2017_t20_Shivam+Chauhan.csv
done for  Ritwik+Chowdhury
done for  Tom+Cooper
score_files/2017_t20_Puneet+Datey.csv
score_files/2017_t20_Sumit+Narwal.csv
score_files/2017_t20_Shivam+Sharma.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Jonathan+Carter.csv
score_files/2017_t20_Dasun+Shanka.csv
score_files/2017_t20_Mahmud+Ullah.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Kuldeep+Hooda.csv
score_files/2017_t20_B.+Indrajith.csv
done for  Dharmendrasinh+Jadeja
score_files/2017_t20_Shubham+Ranjane.csv
done for  Raymon+Reifer
score_files/2017_t20_Atit+Sheth.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Shubam+Agrawal.csv
score_files/2017_t20_Khalid+Ahmad.csv
score_files/2017_t20_Shamar+Springer.csv
score_files/2017_t20_Amit+Verma.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Hiten+Dalal.csv
score_files/2017_t20_Robbie+Frylinck.csv
score_files/2017_t20_Vinay+Galetiya.csv
score_files/2017_t20_Nikhil+Gangta.csv
score_files/2017_t20_Arindam+Ghosh.csv
done for  Christiaan+Jonker
score_files/2017_t20_nan.csv
score_files/2017_t20_Karan+Kaila.csv
done for  Parth+Kohli
score_files/2017_t20_Vishal+Kushwah.csv
score_files/2017_t20_Prerak+Mankad.csv
score_files/2017_t20_Sanjay+Pahal.csv
score_files/2017_t20_Kavish+Panchal.csv
score_files/2017_t20_Diwesh+Pathania.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Shaurya+Sanandia.csv
done for  Hardik+Sethi
score_files/2017_t20_Dhruv+Shorey.csv
score_files/2017_t20_Kaushal+Singh.csv
score_files/2017_t20_Himmat+Singh.csv
score_files/2017_t20_nan.csv
score_files/2017_t20_Nick+Buchanan.csv
score_files/2017_t20_Writtick+Chatterjee.csv
score_files/2017_t20_Rituraj+Singh.csv
score_files/2017_t20_Ankit+Soni.csv
score_files/2017_t20_Varun+Sood.csv
done for  Ashton+Turner
done for  Vysak+V.
score_files/2017_t20_Parikshit+Valsangkar.csv

In [4]:
import math
alldata = pd.DataFrame()
alldata['batsman'] = batsman
alldata['base_price'] = base_price
alldata['runs'] = runs
alldata['balls'] = balls
alldata['avg'] = avg
alldata['srate'] = srate

alldata['runs2'] = runs2
alldata['balls2'] = balls2
alldata['avg2'] = avg2
alldata['srate2'] = srate2

alldata['netruns'] = alldata['runs'] + alldata['runs2']
print len(alldata)
alldata = alldata.dropna(1)
print len(alldata)

64
64

In [5]:
alldata

,batsman,base_price,runs,balls,avg,runs2,balls2,avg2,netruns
0,Faiz+Fazal,30,14,17,7.000000,100,146,20.000000,114
1,Martin+Guptill,50,486,377,25.578947,683,681,40.176471,1169
2,Alex+Hales,100,228,182,20.727273,749,753,49.933333,977
3,Eoin+Morgan,200,827,655,25.843750,700,769,31.818182,1527
4,Jason+Roy,100,898,588,29.933333,1268,1193,42.266667,2166
5,Ross+Taylor,50,673,483,37.388889,248,333,27.555556,921
6,Sean+Abbott,30,53,46,7.571429,62,42,31.000000,115
7,Corey+Anderson,100,467,334,27.470588,87,150,10.875000,554
8,Chris+Jordan,50,197,178,9.380952,172,186,19.111111,369
9,Angelo+Mathews,200,223,212,24.777778,425,509,38.636364,648
10,Benjamin+Stokes,200,209,149,13.062500,553,508,39.500000,762
11,Jonny+Bairstow,150,39,42,9.750000,276,353,25.090909,315
12,Dinesh+Chandimal,50,457,429,25.388889,664,880,47.428571,1121
13,Johnson+Charles,30,702,498,31.909091,304,379,17.882353,1006
14,Ben+Dunk,30,364,222,45.500000,54,70,10.800000,418
15,Andre+Fletcher,30,565,531,23.541667,191,365,14.692308,756
16,Unmukt+Chand,30,64,80,10.666667,197,298,32.833333,261
17,Michael+Klinger,30,882,670,36.750000,573,665,47.750000,1455
18,Mohammad+Nabi,30,513,356,17.100000,216,260,27.000000,729
19,Darren+Bravo,50,79,66,26.333333,312,467,31.200000,391
20,Evin+Lewis,50,489,314,28.764706,319,301,39.875000,808
21,Nic+Maddinson,50,157,148,13.083333,441,514,44.100000,598
22,Marlon+Samuels,100,568,524,29.894737,410,448,34.166667,978
23,Farhaan+Behardien,30,545,336,24.772727,255,291,23.181818,800
24,Jason+Holder,150,22,19,5.500000,295,326,16.388889,317
25,David+Wiese,30,275,181,13.750000,109,99,27.250000,384
26,Chris+Woakes,200,31,27,7.750000,275,250,19.642857,306
27,Niroshan+Dickwella,30,149,97,24.833333,436,404,39.636364,585
28,D'Arcy+Short,10,198,121,24.750000,93,94,23.250000,291
29,Neil+Broom,30,444,350,23.368421,480,518,48.000000,924
...,...,...,...,...,...,...,...,...,...
34,Kusal+Mendis,30,55,43,9.166667,651,738,36.166667,706
35,Daniel+Christian,100,414,274,23.000000,398,367,30.615385,812
36,Grant+Elliott,100,317,263,12.680000,82,109,41.000000,399
37,Colin+Munro,50,744,559,25.655172,172,183,28.666667,916
38,James+Neesham,50,326,226,20.375000,432,440,28.800000,758
39,Wayne+Parnell,50,207,174,13.800000,90,154,9.000000,297
40,Rovman+Powell,30,228,191,19.000000,352,282,32.000000,580
41,Darren+Sammy,30,706,442,17.650000,117,91,29.250000,823
42,Mitchell+Santner,50,157,105,15.700000,123,168,10.250000,280
43,Milind+Kumar,10,66,72,16.500000,49,69,12.250000,115
44,Amit+Mishra,10,4,14,1.333333,15,20,7.500000,19
45,Shashank+Singh,10,430,361,18.695652,266,244,66.500000,696
46,Milind+Tandon,10,430,361,18.695652,266,244,66.500000,696
47,Glenn+Phillips,10,369,258,36.900000,218,262,43.600000,587
48,Amit+Mishra,10,4,14,1.333333,15,20,7.500000,19
49,Anton+Devcich,30,38,40,12.666667,18,17,9.000000,56
50,Rayad+Emrit,30,55,51,6.111111,22,33,7.333333,77
51,Seekkuge+Prasanna,30,236,156,9.833333,207,139,20.700000,443
52,Dwaine+Pretorius,30,52,49,8.666667,41,64,10.250000,93
53,Jesse+Ryder,30,239,191,18.384615,596,674,42.571429,835
54,Alex+Ross,30,250,235,25.000000,85,118,17.000000,335
55,Ritwik+Chowdhury,10,70,63,11.666667,288,340,20.571429,358
56,Tom+Cooper,30,182,125,18.200000,221,256,36.833333,403
57,Dharmendrasinh+Jadeja,10,210,198,10.500000,39,29,13.000000,249
58,Raymon+Reifer,20,15,18,3.750000,114,149,28.500000,129
59,Christiaan+Jonker,10,294,185,26.727273,263,235,52.600000,557
60,Parth+Kohli,10,1467,1018,50.586207,543,528,67.875000,2010
61,Hardik+Sethi,10,144,138,7.578947,211,201,19.181818,355
62,Ashton+Turner,20,123,84,15.375000,62,50,20.666667,185
63,Vysak+V.,10,123,84,15.375000,62,50,20.666667,185

In [9]:
import pickle
from sklearn.externals import joblib


model = joblib.load('model3.pkl')

In [12]:
model.predict(alldata)

ValueError: could not convert string to float: Vysak+V.

In [20]:
cols = ['runs','avg','runs2','base_price','avg2','netruns','avg','runs2','year']

alldata['year'] = 2017
a = alldata[cols]

In [22]:
len(model.predict(a))

64